LIB=compat
SRCS= progname.c errc.c verrc.c setmode.c reallocarr.c utimens.c fchflags.c fgetln.c strsuftoll.c \
	humanize_number.c fgetwln.c vis.c signals.c strmode.c devname.c fts.c expand_number.c

.include "../../mk/lib.mk"
