LIB=compat
SRCS= progname.c errc.c verrc.c setmode.c reallocarr.c utimens.c fchflags.c fgetln.c strsuftoll.c \
	humanize_number.c fgetwln.c vis.c signals.c strmode.c devname.c fts.c expand_number.c \
	getbsize.c compat.c

LDFLAGS += -lacl

CPPFLAGS += -DHAVE_NBTOOL_CONFIG_H
.include "../../mk/lib.mk"
