IMPDIR = libcompat libutil

SUBDIR=	base64 basename cat chmod chown chroot comm cp csplit cut date dd df dirname du echo \
	env expand expr false fmt fold head hexdump hostname id install join kill link ln logname \
	ls mkdir mkfifo mknod mktemp mv nice nl nohup paste pathchk printenv printf pwd realpath \
	renice rm rmdir seq sleep sort split stat stty sync tail tee test timeout touch tr true tsort  \
	tty uname unexpand uniq unlink users wc who yes

.include "../mk/subdir.mk"
