IMPDIR = libnetbsd libutil

SUBDIR =  base64 basename cat chmod chown chroot cksum comm cp csplit cut date dd df
SUBDIR += dirname du echo env expand expr false fmt fold head hexdump hostname id install 
SUBDIR += join kill link ln logname ls mkdir mkfifo mknod mktemp mv nice nl nohup paste 
SUBDIR += pathchk printenv printf pwd realpath renice rm rmdir seq sleep sort split stat 
SUBDIR += sync tail tee test timeout touch tr true tty uname unexpand uniq unlink users wc 
SUBDIR += who yes

.include "../mk/subdir.mk"
